name: "Allowlist GitHub User"

description: "This action sends a POST request to add a new entry in TON Society ID Github allowlist when a given Github user's PR is merged."

inputs:
  github_token:
    description: "GitHub token to comment on PR"
    required: true
  x_api_key:
    description: "API key for authentication"
    required: true
  x_partner_id:
    description: "Partner ID for authentication"
    required: true
  github_user_id:
    description: "The GitHub user ID to be added to the allowlist"
    required: true
  activity_id:
    description: "The activity ID"
    required: true
  xps:
    description: "Optional reward xps"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get install jq -y

    - name: Call Allowlist API and store reward link
      id: call_api
      shell: bash
      run: |
        if [[ -n "${{ inputs.xps }}" ]]; then
          echo "ℹ️ Including xps value: ${{ inputs.xps }}"
          request_body=$(jq -n \
            --arg xps "${{ inputs.xps }}" \
            '{attributes: [{trait_type: "xps", value: $xps}]}')
        else
          echo "ℹ️ No xps provided. Sending empty request body."
          request_body="{}"
        fi

        echo "➡️ Sending POST request..."
        curl_output=$(mktemp)
        http_code=$(curl -s -o "$curl_output" -w "%{http_code}" -X POST "https://society.ton.org/v1/activities/${{ inputs.activity_id }}/allowlist/github-ids/${{ inputs.github_user_id }}" \
          -H "x-api-key: ${{ inputs.x_api_key }}" \
          -H "x-partner-id: ${{ inputs.x_partner_id }}" \
          -H "Content-Type: application/json" \
          -d "$request_body")

        http_body=$(cat "$curl_output")

        echo "HTTP status: $http_code"
        echo "Response body: $http_body"

        if [[ "$http_code" -lt 200 || "$http_code" -ge 300 ]]; then
          echo "❌ API call failed with status $http_code"
          exit 1
        fi

        reward_link=$(echo "$http_body" | jq -r '.data.reward_link_url // empty')

        if [ -z "$reward_link" ]; then
          echo "❌ reward_link_url not found in response."
          exit 1
        fi

        echo "✅ Received reward link: $reward_link"
        echo "reward_link_url=$reward_link" >> "$GITHUB_OUTPUT"

    - name: Comment reward link on PR
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        pr_author=$(jq --raw-output .pull_request.user.login "$GITHUB_EVENT_PATH")
        repo="${{ github.repository }}"
        reward_link="${{ steps.call_api.outputs.reward_link_url }}"

        if [ -z "$reward_link" ]; then
          echo "⚠️ No reward link to comment. Skipping comment step."
          exit 0
        fi

        comment_body="🎉 Hey @${pr_author}, you've been allowlisted! Here’s your reward link: [$reward_link]($reward_link)"

        curl -s -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg body "$comment_body" '{body: $body}')" \
          "https://api.github.com/repos/$repo/issues/$pr_number/comments"
