name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: validate tag format
        id: validate
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          if [[ ! $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag '$TAG' does not match vN.N.N; skipping merge."
            exit 0
          fi
          echo "validated=true" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        if: steps.validate.outputs.validated == 'true'
        with:
          fetch-depth: 0
      - name: update release branch
        if: steps.validate.outputs.validated == 'true'
        shell: bash
        # language=bash
        run: |
          TAG="${{ github.event.release.tag_name }}"
          git fetch origin v1
          git fetch origin "refs/tags/${TAG}:refs/tags/${TAG}"
          git checkout v1
          git merge --ff-only "${TAG}"
          git push origin v1
